### ISSUE TITLE
Users should be able to specify to which namespaces their policies can apply to.

### ISSUE THREAD

**Issue by mvladev** [karydia/karydia#110]
### Description

Right now end-users cannot specify in which namespaces their policies are deployed into.

### User Story

End user creates network policy called `foo` which needs to deployed in namespaced labeled with `foo-policy=enabled`

### [OPTIONAL] Implementation idea

Introduce a new resource called `KarydiaNetworkPolicy` which contains both `NetworkPolicyTemplate` and `Namespace` selector:

```yaml
apiVersion: karydia.gardener.cloud/v1alpha1
kind: KarydiaNetworkPolicy
metadata:
  name: foo
spec:
  namespaceSelector: # LabelSelector https://github.com/kubernetes/api/blob/00c78f6603af046dfcada47ba511ddc94e7a64ce/admissionregistration/v1beta1/types.go#L193
    matchExpressions: 
    - key: foo-policy
      operator: In
      values:
      - enabled
  template: # PodSecurityPolicySpecification https://github.com/kubernetes/api/blob/61630f889b3c3efb8c3a4ba377da1a421d9ff6ce/networking/v1/types.go#L53
    podSelector: {}
    policyTypes:
    - Egress
```

Given that end-user has a namespace:

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: some-namespace
  labels:
    foo-policy: enabled
```

This should produce the following `NetworkPolicy` in namespace `some-namespace`:

```yaml
apiVersion: extensions/v1beta1
kind: NetworkPolicy
metadata:
  name: foo
  namespace: some-namespace
spec:
  podSelector: {}
  policyTypes:
  - Egress
```

**Comment by CodeClinch** [comment]
@mvladev I like your approach, but this would mean that a user has to label the namespace to get the policy. We would like to provide secure by default, which means even so the user forgets the label a network policy should be created. But may be we could at lease use a "black list" version.

**Comment by mvladev** [comment]
@CodeClinch if it should be applied to ALL namespaces than 

```yaml
spec:
  namespaceSelector: {}
``` 

can be used (it selects all namespaces) or

```yaml
spec:
  matchExpressions: 
  - key: role
    operator: NotIn
    values:
    - system
    - logging
``` 

selecting all namespaces, except for those labeled with `role=system` or `role=logging`.
