### ISSUE TITLE
Ability to install karydia via gardener addon

### ISSUE THREAD

**Issue by linuxbsdfreak** [karydia/karydia#226]
### Description
When using Gardener as a platform. It would ideal to enable and disable installation of karydia as a addon

### User Story
As a gardener shoot cluster administrator I want to setup karydia to be installed via and addon  in order to make karydia configurable via the shoot yaml and also the reconciliation of the addon automatic.

### [OPTIONAL] Implementation idea
```
 addons:
    karydia:
      enabled: true
      exclusionObjectLabels:
         - key: "app"
           values:
              - "karydia"
              - "flux"
              - "flux-helm-operator"
              - "flux-memcached"
              - "postgresql" 
```
