### ISSUE TITLE
Don't list all OPA policies on command line

### ISSUE THREAD

**Issue by alban** [karydia/karydia#35]
Files:
- contrib/gardener/scripts/deploy-karydia-cp
- manifests-dev/karydia-dev-telepresence.yml

list all the OPA policies on the command line:
```
      - name: opa
        image: openpolicyagent/opa:0.10.1
        imagePullPolicy: IfNotPresent
        args:
          - "run"
          - "--server"
          - "--addr=http://127.0.0.1:8181"
          - "/etc/opa-policies/parameters.rego"
          - "/etc/opa-policies/default-policy-matches.rego"
          - "/etc/opa-policies/default-kubernetes-matches.rego"
...
```
because I thought it was not possible to avoid loading dotted files from configmaps.

But `opa` has the option `--ignore`:
https://github.com/open-policy-agent/opa/issues/1109#issuecomment-448395503

We should try this.
